version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: /data/gitcontrol/banckend
    container_name: gitcontrol-backend
    restart: unless-stopped
    #env_file:
    #  - ./.env
    ports:
      - 4300:80
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 4300
    volumes:
      - /data:/home/app/repositories
  #     - ./backend/dist:/home/node/app/src
  #     - ./backend/tmp/uploads:/home/node/app/tmp/uploads
    command: ./node_modules/.bin/nodemon ./src/server.js
    networks:
      gitcontrol_network:

  frontend:
    image: nginx:stable-alpine
    container_name: gitcontrol-frontend
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #  - ./frontend/dist:/var/www/public_html
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      rom_network:
        ipv4_address: 171.21.0.30
      gitcontrol_network:

  postgres:
    image: postgres
    container_name: gitcontrol-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      gitcontrol_network:

networks:
  rom_network:
    external: true
  gitcontrol_network:
    driver:
      bridge